services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
  storage_init:
    image: mcr.microsoft.com/azure-cli:latest
    command:
      - /bin/sh
      - -c
      - |
        az storage container create --name rota
        az storage container create --name processing
        az storage blob upload -f /test_files/rota_test_file.xml -c rota -n rota_test_file.xml
    volumes:
      - ./test_files:/test_files
    depends_on:
      azurite:
        condition: service_healthy
    environment:
      # https://github.com/Azure/Azurite/blob/main/README.md#usage-with-azure-storage-sdks-or-tools
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
