server:
  port: 3456

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
        authorization-clients:
          hmiApim:
            authorization-grant-type: client_credentials
            scopes:
              - ${HMI_APIM_AZ_API}/.default

  config:
    import: "optional:configtree:/mnt/secrets/hmi-kv/"
  application:
    name: HMI Rota DTU
  datasource:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

azure:
  blob:
    connection-string: ${CONNECTION_STRING}
    storage-account-name: ${STORAGE_ACCOUNT_NAME}
    rota-container-name: rota
    processing-container-name: processing
  managed-identity:
    client-id: ${MANAGED_IDENTITY_CLIENT_ID:}

service-to-service:
  hmi-apim: ${HMI_APIM}

service-now:
  sn_url: ${SN_URL}
  username: ${SN_USERNAME}
  password: ${SN_PASSWORD}
  assignment_group: ${SN_ASSIGNMENT_GROUP}
  caller_id: ${SN_CALLER_ID}
  service-offering: ${SN_SERVICE_OFFERING}
  role_type: ${SN_ROLE_TYPE}

validations:
  rota-hmi-xsd: "schemas/rota-hmi-interface.xsd"

destination-system: ${DESTINATION_SYSTEM:SNL}
request-limit: ${REQUEST_LIMIT:200}
