server:
  port: 3456

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/hmi-kv/"
  application:
    name: HMI Rota DTU

azure:
  application-insights:
    instrumentation-key: ${hmi.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
  blob:
    connection-string: ${CONNECTION_STRING}
    rota-container-name: rota
    processing-container-name: processing

url: ${URL}
