server:
  port: 3456

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/hmi-kv/"
  application:
    name: HMI Rota DTU
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
        authorization-clients:
          hmiApim:
            authorization-grant-type: client_credentials
            scopes:
              - ${DATA_MANAGEMENT_AZ_API}/.default

azure:
  application-insights:
    instrumentation-key: ${AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:00000000-0000-0000-0000-000000000000}
  blob:
    connection-string: ${CONNECTION_STRING}
    rota-container-name: rota
    processing-container-name: processing

service-to-service:
  hmi-apim: ${HMI_APIM}
