function:
  image: 'sdshmctspublic.azurecr.io/hmi/rota-dtu:latest'
  aadIdentityName: hmi
  keyVaults:
    hmi-kv:
      excludeEnvironmentSuffix: false
      resourceGroup: hmi-sharedinfra-{{ .Values.global.environment }}-rg
      usePodIdentity: true
      secrets:
        - name: sa-connection-string
          alias: CONNECTION_STRING
        - name: app-insights-rota-dtu-instrumentation-key
          alias: AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY
        - name: hmi-url
          alias: HMI_APIM
        - name: tenant-id
          alias: TENANT_ID
        - name: hmi-rota-dtu-id
          alias: CLIENT_ID
        - name: hmi-rota-dtu-pwd
          alias: CLIENT_SECRET
        - name: hmi-gateway-scope
          alias: HMI_APIM_AZ_API

  scaleType: Job
  triggerAuth:
    create: true
    enabled: true
    triggerPodIdentityProvider: "azure"
  triggers:
    - type: azure-blob
      blobContainerName: rota
      blobCount: 1
      accountName: "hmisa{{ .Values.global.environment }}"
      blobDelimiter: "/"
