function:
  image: 'sdshmctspublic.azurecr.io/hmi/rota-dtu:latest'
  aadIdentityName: hmi
  scaleType: Job
  triggerAuth:
    triggerPodIdentityProvider: "azure"
  triggers:
    - type: azure-blob
      blobContainerName: proof-of-concept
      blobCount: 1
      accountName: "hmidtu{{ .Values.global.environment }}"
      blobDelimiter: "/"
