function:
  image: 'sdshmctspublic.azurecr.io/hmi/rota-dtu:latest'
  aadIdentityName: hmi
  keyVaults:
    hmi-kv:
      excludeEnvironmentSuffix: false
      resourceGroup: hmi-sharedinfra-{{ .Values.global.environment }}-rg
      usePodIdentity: true
      secrets:
        - name: sa-connection-string
          alias: CONNECTION_STRING
        - name: app-insights-rota-dtu-connection-string
          alias: AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING
        - name: poc-url
          alias: URL
  scaleType: Job
  triggerAuth:
    create: true
    enabled: true
    triggerPodIdentityProvider: "azure"
  triggers:
    - type: azure-blob
      blobContainerName: rota
      blobCount: 1
      accountName: "hmisa{{ .Values.global.environment }}"
      blobDelimiter: "/"
