function:
  image: 'sdshmctspublic.azurecr.io/hmi/rota-dtu:latest'
  aadIdentityName: hmi
  scaleType: Job
  triggerAuth:
    create: true
    enabled: true
    triggerPodIdentityProvider: "azure"
  triggers:
    - type: azure-blob
      blobContainerName: rota
      blobCount: 1
      accountName: "hmisa{{ .Values.global.environment }}"
      blobDelimiter: "/"
